# Generated by Django 5.2.7 on 2025-11-09 03:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('frases', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='work',
            name='review',
        ),
        migrations.AddField(
            model_name='work',
            name='title',
            field=models.CharField(default='', max_length=200),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='work',
            name='director',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='work',
            name='type',
            field=models.CharField(choices=[('MOVIE', 'Movie'), ('BOOK', 'Book')], help_text='Type of work: MOVIE or BOOK', max_length=10),
        ),
        migrations.AlterModelTable(
            name='quote',
            table='quote',
        ),
        migrations.AlterModelTable(
            name='work',
            table='work',
        ),
    ]
